# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andrewlazenka/Documents/GitHub/JimFarm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andrewlazenka/Documents/GitHub/JimFarm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrewlazenka/Documents/GitHub/JimFarm/CMakeFiles /Users/andrewlazenka/Documents/GitHub/JimFarm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrewlazenka/Documents/GitHub/JimFarm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JimFarm

# Build rule for target.
JimFarm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JimFarm
.PHONY : JimFarm

# fast build rule for target.
JimFarm/fast:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/build
.PHONY : JimFarm/fast

src/Character.o: src/Character.cpp.o

.PHONY : src/Character.o

# target to build an object file
src/Character.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Character.cpp.o
.PHONY : src/Character.cpp.o

src/Character.i: src/Character.cpp.i

.PHONY : src/Character.i

# target to preprocess a source file
src/Character.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Character.cpp.i
.PHONY : src/Character.cpp.i

src/Character.s: src/Character.cpp.s

.PHONY : src/Character.s

# target to generate assembly for a file
src/Character.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Character.cpp.s
.PHONY : src/Character.cpp.s

src/Chunk.o: src/Chunk.cpp.o

.PHONY : src/Chunk.o

# target to build an object file
src/Chunk.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Chunk.cpp.o
.PHONY : src/Chunk.cpp.o

src/Chunk.i: src/Chunk.cpp.i

.PHONY : src/Chunk.i

# target to preprocess a source file
src/Chunk.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Chunk.cpp.i
.PHONY : src/Chunk.cpp.i

src/Chunk.s: src/Chunk.cpp.s

.PHONY : src/Chunk.s

# target to generate assembly for a file
src/Chunk.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Chunk.cpp.s
.PHONY : src/Chunk.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameMenu.o: src/GameMenu.cpp.o

.PHONY : src/GameMenu.o

# target to build an object file
src/GameMenu.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/GameMenu.cpp.o
.PHONY : src/GameMenu.cpp.o

src/GameMenu.i: src/GameMenu.cpp.i

.PHONY : src/GameMenu.i

# target to preprocess a source file
src/GameMenu.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/GameMenu.cpp.i
.PHONY : src/GameMenu.cpp.i

src/GameMenu.s: src/GameMenu.cpp.s

.PHONY : src/GameMenu.s

# target to generate assembly for a file
src/GameMenu.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/GameMenu.cpp.s
.PHONY : src/GameMenu.cpp.s

src/Graphics.o: src/Graphics.cpp.o

.PHONY : src/Graphics.o

# target to build an object file
src/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Graphics.cpp.o
.PHONY : src/Graphics.cpp.o

src/Graphics.i: src/Graphics.cpp.i

.PHONY : src/Graphics.i

# target to preprocess a source file
src/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Graphics.cpp.i
.PHONY : src/Graphics.cpp.i

src/Graphics.s: src/Graphics.cpp.s

.PHONY : src/Graphics.s

# target to generate assembly for a file
src/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Graphics.cpp.s
.PHONY : src/Graphics.cpp.s

src/Inventory.o: src/Inventory.cpp.o

.PHONY : src/Inventory.o

# target to build an object file
src/Inventory.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Inventory.cpp.o
.PHONY : src/Inventory.cpp.o

src/Inventory.i: src/Inventory.cpp.i

.PHONY : src/Inventory.i

# target to preprocess a source file
src/Inventory.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Inventory.cpp.i
.PHONY : src/Inventory.cpp.i

src/Inventory.s: src/Inventory.cpp.s

.PHONY : src/Inventory.s

# target to generate assembly for a file
src/Inventory.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Inventory.cpp.s
.PHONY : src/Inventory.cpp.s

src/Item.o: src/Item.cpp.o

.PHONY : src/Item.o

# target to build an object file
src/Item.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Item.cpp.o
.PHONY : src/Item.cpp.o

src/Item.i: src/Item.cpp.i

.PHONY : src/Item.i

# target to preprocess a source file
src/Item.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Item.cpp.i
.PHONY : src/Item.cpp.i

src/Item.s: src/Item.cpp.s

.PHONY : src/Item.s

# target to generate assembly for a file
src/Item.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Item.cpp.s
.PHONY : src/Item.cpp.s

src/ItemStack.o: src/ItemStack.cpp.o

.PHONY : src/ItemStack.o

# target to build an object file
src/ItemStack.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/ItemStack.cpp.o
.PHONY : src/ItemStack.cpp.o

src/ItemStack.i: src/ItemStack.cpp.i

.PHONY : src/ItemStack.i

# target to preprocess a source file
src/ItemStack.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/ItemStack.cpp.i
.PHONY : src/ItemStack.cpp.i

src/ItemStack.s: src/ItemStack.cpp.s

.PHONY : src/ItemStack.s

# target to generate assembly for a file
src/ItemStack.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/ItemStack.cpp.s
.PHONY : src/ItemStack.cpp.s

src/MapItem.o: src/MapItem.cpp.o

.PHONY : src/MapItem.o

# target to build an object file
src/MapItem.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/MapItem.cpp.o
.PHONY : src/MapItem.cpp.o

src/MapItem.i: src/MapItem.cpp.i

.PHONY : src/MapItem.i

# target to preprocess a source file
src/MapItem.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/MapItem.cpp.i
.PHONY : src/MapItem.cpp.i

src/MapItem.s: src/MapItem.cpp.s

.PHONY : src/MapItem.s

# target to generate assembly for a file
src/MapItem.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/MapItem.cpp.s
.PHONY : src/MapItem.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Messenger.o: src/Messenger.cpp.o

.PHONY : src/Messenger.o

# target to build an object file
src/Messenger.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Messenger.cpp.o
.PHONY : src/Messenger.cpp.o

src/Messenger.i: src/Messenger.cpp.i

.PHONY : src/Messenger.i

# target to preprocess a source file
src/Messenger.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Messenger.cpp.i
.PHONY : src/Messenger.cpp.i

src/Messenger.s: src/Messenger.cpp.s

.PHONY : src/Messenger.s

# target to generate assembly for a file
src/Messenger.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Messenger.cpp.s
.PHONY : src/Messenger.cpp.s

src/SimplexNoise.o: src/SimplexNoise.cpp.o

.PHONY : src/SimplexNoise.o

# target to build an object file
src/SimplexNoise.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/SimplexNoise.cpp.o
.PHONY : src/SimplexNoise.cpp.o

src/SimplexNoise.i: src/SimplexNoise.cpp.i

.PHONY : src/SimplexNoise.i

# target to preprocess a source file
src/SimplexNoise.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/SimplexNoise.cpp.i
.PHONY : src/SimplexNoise.cpp.i

src/SimplexNoise.s: src/SimplexNoise.cpp.s

.PHONY : src/SimplexNoise.s

# target to generate assembly for a file
src/SimplexNoise.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/SimplexNoise.cpp.s
.PHONY : src/SimplexNoise.cpp.s

src/Sprite.o: src/Sprite.cpp.o

.PHONY : src/Sprite.o

# target to build an object file
src/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Sprite.cpp.o
.PHONY : src/Sprite.cpp.o

src/Sprite.i: src/Sprite.cpp.i

.PHONY : src/Sprite.i

# target to preprocess a source file
src/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Sprite.cpp.i
.PHONY : src/Sprite.cpp.i

src/Sprite.s: src/Sprite.cpp.s

.PHONY : src/Sprite.s

# target to generate assembly for a file
src/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Sprite.cpp.s
.PHONY : src/Sprite.cpp.s

src/State.o: src/State.cpp.o

.PHONY : src/State.o

# target to build an object file
src/State.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/State.cpp.o
.PHONY : src/State.cpp.o

src/State.i: src/State.cpp.i

.PHONY : src/State.i

# target to preprocess a source file
src/State.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/State.cpp.i
.PHONY : src/State.cpp.i

src/State.s: src/State.cpp.s

.PHONY : src/State.s

# target to generate assembly for a file
src/State.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/State.cpp.s
.PHONY : src/State.cpp.s

src/Tile.o: src/Tile.cpp.o

.PHONY : src/Tile.o

# target to build an object file
src/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Tile.cpp.o
.PHONY : src/Tile.cpp.o

src/Tile.i: src/Tile.cpp.i

.PHONY : src/Tile.i

# target to preprocess a source file
src/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Tile.cpp.i
.PHONY : src/Tile.cpp.i

src/Tile.s: src/Tile.cpp.s

.PHONY : src/Tile.s

# target to generate assembly for a file
src/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/Tile.cpp.s
.PHONY : src/Tile.cpp.s

src/TileMap.o: src/TileMap.cpp.o

.PHONY : src/TileMap.o

# target to build an object file
src/TileMap.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/TileMap.cpp.o
.PHONY : src/TileMap.cpp.o

src/TileMap.i: src/TileMap.cpp.i

.PHONY : src/TileMap.i

# target to preprocess a source file
src/TileMap.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/TileMap.cpp.i
.PHONY : src/TileMap.cpp.i

src/TileMap.s: src/TileMap.cpp.s

.PHONY : src/TileMap.s

# target to generate assembly for a file
src/TileMap.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/TileMap.cpp.s
.PHONY : src/TileMap.cpp.s

src/UI_Controller.o: src/UI_Controller.cpp.o

.PHONY : src/UI_Controller.o

# target to build an object file
src/UI_Controller.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Controller.cpp.o
.PHONY : src/UI_Controller.cpp.o

src/UI_Controller.i: src/UI_Controller.cpp.i

.PHONY : src/UI_Controller.i

# target to preprocess a source file
src/UI_Controller.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Controller.cpp.i
.PHONY : src/UI_Controller.cpp.i

src/UI_Controller.s: src/UI_Controller.cpp.s

.PHONY : src/UI_Controller.s

# target to generate assembly for a file
src/UI_Controller.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Controller.cpp.s
.PHONY : src/UI_Controller.cpp.s

src/UI_Element.o: src/UI_Element.cpp.o

.PHONY : src/UI_Element.o

# target to build an object file
src/UI_Element.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Element.cpp.o
.PHONY : src/UI_Element.cpp.o

src/UI_Element.i: src/UI_Element.cpp.i

.PHONY : src/UI_Element.i

# target to preprocess a source file
src/UI_Element.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Element.cpp.i
.PHONY : src/UI_Element.cpp.i

src/UI_Element.s: src/UI_Element.cpp.s

.PHONY : src/UI_Element.s

# target to generate assembly for a file
src/UI_Element.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Element.cpp.s
.PHONY : src/UI_Element.cpp.s

src/UI_Label.o: src/UI_Label.cpp.o

.PHONY : src/UI_Label.o

# target to build an object file
src/UI_Label.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Label.cpp.o
.PHONY : src/UI_Label.cpp.o

src/UI_Label.i: src/UI_Label.cpp.i

.PHONY : src/UI_Label.i

# target to preprocess a source file
src/UI_Label.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Label.cpp.i
.PHONY : src/UI_Label.cpp.i

src/UI_Label.s: src/UI_Label.cpp.s

.PHONY : src/UI_Label.s

# target to generate assembly for a file
src/UI_Label.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Label.cpp.s
.PHONY : src/UI_Label.cpp.s

src/UI_Slot.o: src/UI_Slot.cpp.o

.PHONY : src/UI_Slot.o

# target to build an object file
src/UI_Slot.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Slot.cpp.o
.PHONY : src/UI_Slot.cpp.o

src/UI_Slot.i: src/UI_Slot.cpp.i

.PHONY : src/UI_Slot.i

# target to preprocess a source file
src/UI_Slot.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Slot.cpp.i
.PHONY : src/UI_Slot.cpp.i

src/UI_Slot.s: src/UI_Slot.cpp.s

.PHONY : src/UI_Slot.s

# target to generate assembly for a file
src/UI_Slot.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/UI_Slot.cpp.s
.PHONY : src/UI_Slot.cpp.s

src/World.o: src/World.cpp.o

.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i

.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s

.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/manager/InterfaceTypeManager.o: src/manager/InterfaceTypeManager.cpp.o

.PHONY : src/manager/InterfaceTypeManager.o

# target to build an object file
src/manager/InterfaceTypeManager.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/InterfaceTypeManager.cpp.o
.PHONY : src/manager/InterfaceTypeManager.cpp.o

src/manager/InterfaceTypeManager.i: src/manager/InterfaceTypeManager.cpp.i

.PHONY : src/manager/InterfaceTypeManager.i

# target to preprocess a source file
src/manager/InterfaceTypeManager.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/InterfaceTypeManager.cpp.i
.PHONY : src/manager/InterfaceTypeManager.cpp.i

src/manager/InterfaceTypeManager.s: src/manager/InterfaceTypeManager.cpp.s

.PHONY : src/manager/InterfaceTypeManager.s

# target to generate assembly for a file
src/manager/InterfaceTypeManager.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/InterfaceTypeManager.cpp.s
.PHONY : src/manager/InterfaceTypeManager.cpp.s

src/manager/ItemTypeManager.o: src/manager/ItemTypeManager.cpp.o

.PHONY : src/manager/ItemTypeManager.o

# target to build an object file
src/manager/ItemTypeManager.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/ItemTypeManager.cpp.o
.PHONY : src/manager/ItemTypeManager.cpp.o

src/manager/ItemTypeManager.i: src/manager/ItemTypeManager.cpp.i

.PHONY : src/manager/ItemTypeManager.i

# target to preprocess a source file
src/manager/ItemTypeManager.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/ItemTypeManager.cpp.i
.PHONY : src/manager/ItemTypeManager.cpp.i

src/manager/ItemTypeManager.s: src/manager/ItemTypeManager.cpp.s

.PHONY : src/manager/ItemTypeManager.s

# target to generate assembly for a file
src/manager/ItemTypeManager.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/ItemTypeManager.cpp.s
.PHONY : src/manager/ItemTypeManager.cpp.s

src/manager/SoundManager.o: src/manager/SoundManager.cpp.o

.PHONY : src/manager/SoundManager.o

# target to build an object file
src/manager/SoundManager.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/SoundManager.cpp.o
.PHONY : src/manager/SoundManager.cpp.o

src/manager/SoundManager.i: src/manager/SoundManager.cpp.i

.PHONY : src/manager/SoundManager.i

# target to preprocess a source file
src/manager/SoundManager.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/SoundManager.cpp.i
.PHONY : src/manager/SoundManager.cpp.i

src/manager/SoundManager.s: src/manager/SoundManager.cpp.s

.PHONY : src/manager/SoundManager.s

# target to generate assembly for a file
src/manager/SoundManager.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/SoundManager.cpp.s
.PHONY : src/manager/SoundManager.cpp.s

src/manager/TileType.o: src/manager/TileType.cpp.o

.PHONY : src/manager/TileType.o

# target to build an object file
src/manager/TileType.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/TileType.cpp.o
.PHONY : src/manager/TileType.cpp.o

src/manager/TileType.i: src/manager/TileType.cpp.i

.PHONY : src/manager/TileType.i

# target to preprocess a source file
src/manager/TileType.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/TileType.cpp.i
.PHONY : src/manager/TileType.cpp.i

src/manager/TileType.s: src/manager/TileType.cpp.s

.PHONY : src/manager/TileType.s

# target to generate assembly for a file
src/manager/TileType.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/TileType.cpp.s
.PHONY : src/manager/TileType.cpp.s

src/manager/TileTypeManager.o: src/manager/TileTypeManager.cpp.o

.PHONY : src/manager/TileTypeManager.o

# target to build an object file
src/manager/TileTypeManager.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/TileTypeManager.cpp.o
.PHONY : src/manager/TileTypeManager.cpp.o

src/manager/TileTypeManager.i: src/manager/TileTypeManager.cpp.i

.PHONY : src/manager/TileTypeManager.i

# target to preprocess a source file
src/manager/TileTypeManager.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/TileTypeManager.cpp.i
.PHONY : src/manager/TileTypeManager.cpp.i

src/manager/TileTypeManager.s: src/manager/TileTypeManager.cpp.s

.PHONY : src/manager/TileTypeManager.s

# target to generate assembly for a file
src/manager/TileTypeManager.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/manager/TileTypeManager.cpp.s
.PHONY : src/manager/TileTypeManager.cpp.s

src/utility/KeyListener.o: src/utility/KeyListener.cpp.o

.PHONY : src/utility/KeyListener.o

# target to build an object file
src/utility/KeyListener.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/KeyListener.cpp.o
.PHONY : src/utility/KeyListener.cpp.o

src/utility/KeyListener.i: src/utility/KeyListener.cpp.i

.PHONY : src/utility/KeyListener.i

# target to preprocess a source file
src/utility/KeyListener.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/KeyListener.cpp.i
.PHONY : src/utility/KeyListener.cpp.i

src/utility/KeyListener.s: src/utility/KeyListener.cpp.s

.PHONY : src/utility/KeyListener.s

# target to generate assembly for a file
src/utility/KeyListener.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/KeyListener.cpp.s
.PHONY : src/utility/KeyListener.cpp.s

src/utility/MouseListener.o: src/utility/MouseListener.cpp.o

.PHONY : src/utility/MouseListener.o

# target to build an object file
src/utility/MouseListener.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/MouseListener.cpp.o
.PHONY : src/utility/MouseListener.cpp.o

src/utility/MouseListener.i: src/utility/MouseListener.cpp.i

.PHONY : src/utility/MouseListener.i

# target to preprocess a source file
src/utility/MouseListener.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/MouseListener.cpp.i
.PHONY : src/utility/MouseListener.cpp.i

src/utility/MouseListener.s: src/utility/MouseListener.cpp.s

.PHONY : src/utility/MouseListener.s

# target to generate assembly for a file
src/utility/MouseListener.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/MouseListener.cpp.s
.PHONY : src/utility/MouseListener.cpp.s

src/utility/Tools.o: src/utility/Tools.cpp.o

.PHONY : src/utility/Tools.o

# target to build an object file
src/utility/Tools.cpp.o:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/Tools.cpp.o
.PHONY : src/utility/Tools.cpp.o

src/utility/Tools.i: src/utility/Tools.cpp.i

.PHONY : src/utility/Tools.i

# target to preprocess a source file
src/utility/Tools.cpp.i:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/Tools.cpp.i
.PHONY : src/utility/Tools.cpp.i

src/utility/Tools.s: src/utility/Tools.cpp.s

.PHONY : src/utility/Tools.s

# target to generate assembly for a file
src/utility/Tools.cpp.s:
	$(MAKE) -f CMakeFiles/JimFarm.dir/build.make CMakeFiles/JimFarm.dir/src/utility/Tools.cpp.s
.PHONY : src/utility/Tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... JimFarm"
	@echo "... src/Character.o"
	@echo "... src/Character.i"
	@echo "... src/Character.s"
	@echo "... src/Chunk.o"
	@echo "... src/Chunk.i"
	@echo "... src/Chunk.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameMenu.o"
	@echo "... src/GameMenu.i"
	@echo "... src/GameMenu.s"
	@echo "... src/Graphics.o"
	@echo "... src/Graphics.i"
	@echo "... src/Graphics.s"
	@echo "... src/Inventory.o"
	@echo "... src/Inventory.i"
	@echo "... src/Inventory.s"
	@echo "... src/Item.o"
	@echo "... src/Item.i"
	@echo "... src/Item.s"
	@echo "... src/ItemStack.o"
	@echo "... src/ItemStack.i"
	@echo "... src/ItemStack.s"
	@echo "... src/MapItem.o"
	@echo "... src/MapItem.i"
	@echo "... src/MapItem.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/Messenger.o"
	@echo "... src/Messenger.i"
	@echo "... src/Messenger.s"
	@echo "... src/SimplexNoise.o"
	@echo "... src/SimplexNoise.i"
	@echo "... src/SimplexNoise.s"
	@echo "... src/Sprite.o"
	@echo "... src/Sprite.i"
	@echo "... src/Sprite.s"
	@echo "... src/State.o"
	@echo "... src/State.i"
	@echo "... src/State.s"
	@echo "... src/Tile.o"
	@echo "... src/Tile.i"
	@echo "... src/Tile.s"
	@echo "... src/TileMap.o"
	@echo "... src/TileMap.i"
	@echo "... src/TileMap.s"
	@echo "... src/UI_Controller.o"
	@echo "... src/UI_Controller.i"
	@echo "... src/UI_Controller.s"
	@echo "... src/UI_Element.o"
	@echo "... src/UI_Element.i"
	@echo "... src/UI_Element.s"
	@echo "... src/UI_Label.o"
	@echo "... src/UI_Label.i"
	@echo "... src/UI_Label.s"
	@echo "... src/UI_Slot.o"
	@echo "... src/UI_Slot.i"
	@echo "... src/UI_Slot.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/manager/InterfaceTypeManager.o"
	@echo "... src/manager/InterfaceTypeManager.i"
	@echo "... src/manager/InterfaceTypeManager.s"
	@echo "... src/manager/ItemTypeManager.o"
	@echo "... src/manager/ItemTypeManager.i"
	@echo "... src/manager/ItemTypeManager.s"
	@echo "... src/manager/SoundManager.o"
	@echo "... src/manager/SoundManager.i"
	@echo "... src/manager/SoundManager.s"
	@echo "... src/manager/TileType.o"
	@echo "... src/manager/TileType.i"
	@echo "... src/manager/TileType.s"
	@echo "... src/manager/TileTypeManager.o"
	@echo "... src/manager/TileTypeManager.i"
	@echo "... src/manager/TileTypeManager.s"
	@echo "... src/utility/KeyListener.o"
	@echo "... src/utility/KeyListener.i"
	@echo "... src/utility/KeyListener.s"
	@echo "... src/utility/MouseListener.o"
	@echo "... src/utility/MouseListener.i"
	@echo "... src/utility/MouseListener.s"
	@echo "... src/utility/Tools.o"
	@echo "... src/utility/Tools.i"
	@echo "... src/utility/Tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

