name: Build Web

on:
  push:
    branches:
      - main

env:
  EM_VERSION: "latest"
  EM_CACHE_FOLDER: "emsdk-cache"

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Run CMake
        run: emcmake cmake -G "Unix Makefiles" .

      - name: Make
        run: emmake make -j4

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          single-commit: true
